CREATE TABLE Words (
    word_id INT PRIMARY KEY,
    word VARCHAR(255),
    category VARCHAR(255),
    definition VARCHAR(255)
);

INSERT INTO Words (word_id, word, category, definition) VALUES
(1, 'voiture', 'Transport', 'Moyen de déplacement terrestre à moteur'),
(2, 'maison', 'Habitat', 'Lieu où l'on habite'),
(3, 'chien', 'Animaux', 'Un animal domestique souvent loyal'),
(4, 'ordinateur', 'Technologie', 'Appareil électronique pour traiter des données'),
(5, 'fleur', 'Nature', 'Partie d'une plante utilisée pour sa beauté'),
(6, 'école', 'Éducation', 'Lieu où l'on apprend'),
(7, 'pizza', 'Nourriture', 'Un plat italien avec de la pâte et divers garnitures'),
(8, 'football', 'Sports', 'Un jeu d'équipe joué avec un ballon'),
(9, 'livre', 'Culture', 'Un ensemble de pages reliées contenant des informations ou une histoire'),
(10, 'avion', 'Transport', 'Un véhicule qui vole dans les airs'),
(11, 'téléphone', 'Technologie', 'Appareil de communication électronique'),
(12, 'famille', 'Société', 'Un groupe de personnes liées par des liens de parenté'),
(13, 'soleil', 'Astronomie', 'L'étoile centrale de notre système solaire'),
(14, 'forêt', 'Environnement', 'Un grand espace boisé'),
(15, 'argent', 'Finance', 'Une unité de paiement ou de valeur'),
(16, 'hôpital', 'Santé', 'Un établissement médical pour soigner les malades'),
(17, 'banane', 'Aliments', 'Un fruit jaune et courbé'),
(18, 'cinéma', 'Loisirs', 'Un lieu pour regarder des films'),
(19, 'musique', 'Art', 'Expression artistique par le son'),
(20, 'internet', 'Technologie', 'Réseau mondial d'ordinateurs interconnectés'),
(21, 'montagne', 'Géographie', 'Une grande élévation de terrain'),
(22, 'plage', 'Loisirs', 'Bord de mer où l'on peut se détendre'),
(23, 'voyage', 'Loisirs', 'Déplacement d'un endroit à un autre'),
(24, 'restaurant', 'Nourriture', 'Un établissement où l'on peut manger'),
(25, 'fête', 'Célébration', 'Un événement joyeux avec des gens'),
(26, 'amour', 'Émotions', 'Un sentiment profond de tendresse et d'affection'),
(27, 'rêve', 'Psychologie', 'Une expérience de pensée imaginative pendant le sommeil'),
(28, 'froid', 'Météorologie', 'Une température basse'),
(29, 'printemps', 'Saisons', 'La période entre l'hiver et l'été'),
(30, 'réveil', 'Temps', 'Un dispositif pour se réveiller le matin'),
(31, 'cirque', 'Spectacle', 'Un spectacle avec des acrobates et des clowns'),
(32, 'magasin', 'Commerce', 'Un lieu où l'on peut acheter des biens'),
(33, 'pomme', 'Aliments', 'Un fruit croquant et juteux'),
(34, 'chemin', 'Géographie', 'Un itinéraire ou une voie pour se déplacer'),
(35, 'étoile', 'Astronomie', 'Un objet lumineux dans le ciel nocturne'),
(36, 'calme', 'État d'esprit', 'Un état de tranquillité ou de silence'),
(37, 'sourire', 'Expressions faciales', 'Une expression du visage qui montre de la joie'),
(38, 'ocean', 'Géographie', 'Une grande étendue d'eau salée'),
(39, 'papillon', 'Animaux', 'Un insecte ailé souvent coloré'),
(40, 'hiver', 'Saisons', 'La saison froide de l'année'),
(41, 'piano', 'Musique', 'Un instrument de musique à cordes frappées'),
(42, 'parc', 'Loisirs', 'Un espace public aménagé pour la détente'),
(43, 'héros', 'Fiction', 'Un personnage courageux et admirable'),
(44, 'robe', 'Mode', 'Un vêtement féminin souvent porté lors d'occasions spéciales'),
(45, 'ordinateur', 'Technologie', 'Appareil électronique pour traiter des données'),
(46, 'gâteau', 'Nourriture', 'Un dessert sucré souvent cuit au four'),
(47, 'rivières', 'Géographie', 'Un cours d'eau naturel plus petit qu'un fleuve'),
(48, 'passion', 'Émotions', 'Un fort intérêt ou enthousiasme pour quelque chose'),
(49, 'science', 'Éducation', 'Étude de la nature et du monde physique'),
(50, 'jardin', 'Nature', 'Un espace extérieur aménagé avec des plantes et des fleurs');

INSERT INTO Words (word_id, word, category, definition) VALUES
(51, 'chocolat', 'Aliments', 'Une douceur sucrée souvent faite à partir de cacao'),
(52, 'football', 'Sports', 'Un jeu d'équipe joué avec un ballon'),
(53, 'chanson', 'Musique', 'Une composition musicale chantée'),
(54, 'arbre', 'Nature', 'Une plante vivante avec un tronc et des branches'),
(55, 'vacances', 'Loisirs', 'Une période de repos ou de congé du travail ou de l'école'),
(56, 'voyage', 'Loisirs', 'Déplacement d'un endroit à un autre'),
(57, 'héros', 'Fiction', 'Un personnage courageux et admirable'),
(58, 'lune', 'Astronomie', 'Le satellite naturel de la Terre'),
(59, 'amour', 'Émotions', 'Un sentiment profond de tendresse et d'affection'),
(60, 'fruits', 'Aliments', 'Produits comestibles issus de plantes'),
(61, 'cadeau', 'Célébration', 'Un objet offert à quelqu'un pour une occasion spéciale'),
(62, 'pluie', 'Météorologie', 'Des gouttes d'eau tombant du ciel'),
(63, 'oiseau', 'Animaux', 'Un animal volant avec des plumes'),
(64, 'météo', 'Météorologie', 'Les conditions atmosphériques dans une région à un moment donné'),
(65, 'fête', 'Célébration', 'Un événement joyeux avec des gens'),
(66, 'soleil', 'Astronomie', 'L'étoile centrale de notre système solaire'),
(67, 'piscine', 'Loisirs', 'Un bassin artificiel rempli d'eau pour nager'),
(68, 'lac', 'Géographie', 'Une grande étendue d'eau douce'),
(69, 'jeux', 'Loisirs', 'Activités ludiques ou compétitives'),
(70, 'santé', 'Bien-être', 'L'état physique et mental d'une personne'),
(71, 'bonheur', 'Émotions', 'Un état de bien-être et de satisfaction'),
(72, 'montagne', 'Géographie', 'Une grande élévation de terrain'),
(73, 'château', 'Architecture', 'Un grand bâtiment fortifié'),
(74, 'magasin', 'Commerce', 'Un lieu où l'on peut acheter des biens'),
(75, 'maillot', 'Vêtements', 'Un vêtement porté sur le corps'),
(76, 'île', 'Géographie', 'Une masse de terre entourée d'eau'),
(77, 'mer', 'Géographie', 'Une grande étendue d'eau salée'),
(78, 'café', 'Boissons', 'Une boisson chaude souvent faite à partir de grains de café'),
(79, 'livre', 'Culture', 'Un ensemble de pages reliées contenant des informations ou une histoire'),
(80, 'voyage', 'Loisirs', 'Déplacement d'un endroit à un autre'),
(81, 'vélo', 'Transport', 'Un moyen de transport à deux roues'),
(82, 'sourire', 'Expressions faciales', 'Une expression du visage qui montre de la joie'),
(83, 'école', 'Éducation', 'Lieu où l'on apprend'),
(84, 'banane', 'Aliments', 'Un fruit jaune et courbé'),
(85, 'étoile', 'Astronomie', 'Un objet lumineux dans le ciel nocturne'),
(86, 'cinéma', 'Loisirs', 'Un lieu pour regarder des films'),
(87, 'cœur', 'Anatomie', 'Un organe vital dans le corps humain'),
(88, 'bonjour', 'Salutation', 'Un mot utilisé pour dire bonjour'),
(89, 'chapeau', 'Vêtements', 'Un accessoire porté sur la tête'),
(90, 'feu', 'Éléments', 'La chaleur et la lumière produites par la combustion'),
(91, 'chemin', 'Géographie', 'Un itinéraire ou une voie pour se déplacer'),
(92, 'hiver', 'Saisons', 'La saison froide de l'année'),
(93, 'musique', 'Art', 'Expression artistique par le son'),
(94, 'fleur', 'Nature', 'Partie d'une plante utilisée pour sa beauté'),
(95, 'oiseau', 'Animaux', 'Un animal volant avec des plumes'),
(96, 'faim', 'État d'esprit', 'Un besoin physiologique de manger'),
(97, 'cuisine', 'Activités', 'L'art de préparer et de cuisiner des aliments'),
(98, 'heure', 'Temps', 'Unité de mesure du temps'),
(99, 'étoile', 'Astronomie', 'Un objet lumineux dans le ciel nocturne'),
(100, 'maison', 'Habitat', 'Lieu où l'on habite');

INSERT INTO Words (word_id, word, category, definition) VALUES
(101, 'plante', 'Nature', 'Un organisme végétal'),
(102, 'sable', 'Géographie', 'Petites particules de roche utilisées pour former des plages'),
(103, 'rouge', 'Couleurs', 'Une couleur primaire'),
(104, 'araignée', 'Animaux', 'Un petit arthropode à huit pattes'),
(105, 'oiseau', 'Animaux', 'Un animal volant avec des plumes'),
(106, 'chapeau', 'Vêtements', 'Un accessoire porté sur la tête'),
(107, 'table', 'Mobilier', 'Un meuble plat avec des jambes pour supporter des objets'),
(108, 'couteau', 'Outils', 'Un outil tranchant utilisé pour couper'),
(109, 'amour', 'Émotions', 'Un sentiment profond de tendresse et d'affection'),
(110, 'lumière', 'Physique', 'L'agent physique qui rend les objets visibles'),
(111, 'couleur', 'Art', 'Une caractéristique visuelle des objets'),
(112, 'horloge', 'Temps', 'Un dispositif pour mesurer le temps'),
(113, 'voix', 'Son', 'Son produit par les cordes vocales'),
(114, 'cheminée', 'Architecture', 'Une structure pour évacuer la fumée des feux'),
(115, 'route', 'Géographie', 'Un chemin ou une voie pour se déplacer'),
(116, 'mer', 'Géographie', 'Une grande étendue d'eau salée'),
(117, 'carte', 'Papeterie', 'Un morceau de papier avec des informations ou des illustrations'),
(118, 'chaussure', 'Vêtements', 'Un accessoire porté sur le pied'),
(119, 'roue', 'Objets', 'Un cercle tournant qui permet le mouvement'),
(120, 'étoile', 'Astronomie', 'Un objet lumineux dans le ciel nocturne'),
(121, 'tablette', 'Technologie', 'Un petit ordinateur portable avec un écran tactile'),
(122, 'bateau', 'Transport', 'Un véhicule flottant utilisé pour naviguer sur l'eau'),
(123, 'guitare', 'Musique', 'Un instrument à cordes pincées'),
(124, 'télévision', 'Technologie', 'Un appareil pour recevoir des signaux audiovisuels'),
(125, 'vent', 'Météorologie', 'Le mouvement de l'air dans l'atmosphère'),
(126, 'éléphant', 'Animaux', 'Un grand mammifère avec une trompe'),
(127, 'ordinateur', 'Technologie', 'Appareil électronique pour traiter des données'),
(128, 'pain', 'Aliments', 'Un aliment de base fait à partir de farine'),
(129, 'eau', 'Nourriture', 'Un liquide transparent nécessaire à la vie'),
(130, 'jardin', 'Nature', 'Un espace extérieur aménagé avec des plantes et des fleurs'),
(131, 'voiture', 'Transport', 'Moyen de déplacement terrestre à moteur'),
(132, 'souris', 'Animaux', 'Un petit mammifère rongeur'),
(133, 'porte', 'Architecture', 'Un dispositif pour fermer une ouverture'),
(134, 'lune', 'Astronomie', 'Le satellite naturel de la Terre'),
(135, 'cheval', 'Animaux', 'Un grand mammifère utilisé comme moyen de transport ou de travail'),
(136, 'robe', 'Mode', 'Un vêtement féminin souvent porté lors d'occasions spéciales'),
(137, 'ciel', 'Astronomie', 'L'espace visible au-dessus de la Terre'),
(138, 'livre', 'Culture', 'Un ensemble de pages reliées contenant des informations ou une histoire'),
(139, 'pied', 'Anatomie', 'Partie du corps humain utilisée pour marcher'),
(140, 'maison', 'Habitat', 'Lieu où l'on habite'),
(141, 'fleur', 'Nature', 'Partie d'une plante utilisée pour sa beauté'),
(142, 'lumière', 'Physique', 'L'agent physique qui rend les objets visibles'),
(143, 'lit', 'Mobilier', 'Un meuble utilisé pour dormir ou se reposer'),
(144, 'fruit', 'Aliments', 'Produits comestibles issus de plantes'),
(145, 'chocolat', 'Aliments', 'Une douceur sucrée souvent faite à partir de cacao');

INSERT INTO Words (word_id, word, category, definition) VALUES
(146, 'clé', 'Outils', 'Un petit outil utilisé pour ouvrir ou fermer une serrure'),
(147, 'salle', 'Architecture', 'Un espace clos à l'intérieur d'un bâtiment'),
(148, 'chemise', 'Vêtements', 'Un vêtement porté sur le torse'),
(149, 'étoile', 'Astronomie', 'Un objet lumineux dans le ciel nocturne'),
(150, 'lait', 'Nourriture', 'Un liquide blanc produit par les mammifères'),
(151, 'bouteille', 'Contenants', 'Un récipient pour stocker des liquides'),
(152, 'carte', 'Papeterie', 'Un morceau de papier avec des informations ou des illustrations'),
(153, 'crayon', 'Écriture', 'Un outil pour écrire ou dessiner'),
(154, 'téléphone', 'Technologie', 'Appareil de communication électronique'),
(155, 'journal', 'Médias', 'Une publication imprimée contenant des nouvelles ou des informations'),
(156, 'caméra', 'Technologie', 'Un appareil pour enregistrer des images ou des vidéos'),
(157, 'sourire', 'Expressions faciales', 'Une expression du visage qui montre de la joie'),
(158, 'sac', 'Accessoires', 'Un conteneur portatif utilisé pour transporter des objets'),
(159, 'piano', 'Musique', 'Un instrument de musique à cordes frappées'),
(160, 'montre', 'Accessoires', 'Un dispositif pour mesurer le temps'),
(161, 'porte', 'Architecture', 'Un dispositif pour fermer une ouverture'),
(162, 'manteau', 'Vêtements', 'Un vêtement porté sur le corps pour se protéger du froid'),
(163, 'voiture', 'Transport', 'Moyen de déplacement terrestre à moteur'),
(164, 'verre', 'Contenants', 'Un récipient transparent utilisé pour boire'),
(165, 'ordinateur', 'Technologie', 'Appareil électronique pour traiter des données'),
(166, 'arbre', 'Nature', 'Une plante vivante avec un tronc et des branches'),
(167, 'chapeau', 'Vêtements', 'Un accessoire porté sur la tête'),
(168, 'gâteau', 'Nourriture', 'Un dessert sucré souvent cuit au four'),
(169, 'football', 'Sports', 'Un jeu d'équipe joué avec un ballon'),
(170, 'oiseau', 'Animaux', 'Un animal volant avec des plumes'),
(171, 'jardin', 'Nature', 'Un espace extérieur aménagé avec des plantes et des fleurs'),
(172, 'feu', 'Éléments', 'La chaleur et la lumière produites par la combustion'),
(173, 'cœur', 'Anatomie', 'Un organe vital dans le corps humain'),
(174, 'photo', 'Art', 'Une image capturée par une caméra'),
(175, 'vélo', 'Transport', 'Un moyen de transport à deux roues'),
(176, 'papier', 'Matériaux', 'Une feuille mince utilisée pour écrire ou emballer'),
(177, 'maison', 'Habitat', 'Lieu où l'on habite'),
(178, 'école', 'Éducation', 'Lieu où l'on apprend'),
(179, 'pomme', 'Aliments', 'Un fruit croquant et juteux'),
(180, 'jour', 'Temps', 'La période de temps pendant laquelle le soleil est au-dessus de l'horizon'),
(181, 'lune', 'Astronomie', 'Le satellite naturel de la Terre'),
(182, 'crayon', 'Écriture', 'Un outil pour écrire ou dessiner'),
(183, 'montagne', 'Géographie', 'Une grande élévation de terrain'),
(184, 'télévision', 'Technologie', 'Un appareil pour recevoir des signaux audiovisuels'),
(185, 'main', 'Anatomie', 'Une partie du corps humain utilisée pour saisir'),
(186, 'piscine', 'Loisirs', 'Un bassin artificiel rempli d'eau pour nager'),
(187, 'terre', 'Géographie', 'La planète sur laquelle nous

INSERT INTO Words (word_id, word, category, definition) VALUES
(188, 'chat', 'Animaux', 'Un mammifère domestique souvent aimé par les gens'),
(189, 'musique', 'Art', 'Expression artistique par le son'),
(190, 'livre', 'Culture', 'Un ensemble de pages reliées contenant des informations ou une histoire'),
(191, 'soleil', 'Astronomie', 'L'étoile centrale de notre système solaire'),
(192, 'banane', 'Aliments', 'Un fruit jaune et courbé'),
(193, 'jeu', 'Loisirs', 'Activité divertissante avec des règles'),
(194, 'eau', 'Nourriture', 'Un liquide transparent nécessaire à la vie'),
(195, 'papillon', 'Animaux', 'Un insecte ailé souvent coloré'),
(196, 'chocolat', 'Aliments', 'Une douceur sucrée souvent faite à partir de cacao'),
(197, 'chemin', 'Géographie', 'Un itinéraire ou une voie pour se déplacer'),
(198, 'étoile', 'Astronomie', 'Un objet lumineux dans le ciel nocturne'),
(199, 'fleur', 'Nature', 'Partie d'une plante utilisée pour sa beauté'),
(200, 'avion', 'Transport', 'Un véhicule qui vole dans les airs'),
(201, 'plage', 'Nature', 'Bord de mer où l'on peut se détendre'),
(202, 'balle', 'Sports', 'Un petit objet rond utilisé pour jouer'),
(203, 'danse', 'Loisirs', 'Mouvements rythmiques du corps en musique'),
(204, 'loup', 'Animaux', 'Un mammifère carnivore de la famille des canidés'),
(205, 'fête', 'Célébration', 'Un événement joyeux avec des gens'),
(206, 'crayon', 'Écriture', 'Un outil pour écrire ou dessiner'),
(207, 'cuisine', 'Activités', 'L'art de préparer et de cuisiner des aliments'),
(208, 'restaurant', 'Nourriture', 'Un établissement où l'on peut manger'),
(209, 'livre', 'Culture', 'Un ensemble de pages reliées contenant des informations ou une histoire'),
(210, 'bateau', 'Transport', 'Un véhicule flottant utilisé pour naviguer sur l'eau'),
(211, 'escalier', 'Architecture', 'Une structure pour monter ou descendre entre les étages'),
(212, 'loup', 'Animaux', 'Un mammifère carnivore de la famille des canidés'),
(213, 'couleur', 'Art', 'Une caractéristique visuelle des objets'),
(214, 'table', 'Mobilier', 'Un meuble plat avec des jambes pour supporter des objets'),
(215, 'pluie', 'Météorologie', 'Des gouttes d'eau tombant du ciel'),
(216, 'livre', 'Culture', 'Un ensemble de pages reliées contenant des informations ou une histoire'),
(217, 'télévision', 'Technologie', 'Un appareil pour recevoir des signaux audiovisuels'),
(218, 'mère', 'Famille', 'Femme qui a donné naissance à un enfant'),
(219, 'lit', 'Mobilier', 'Un meuble utilisé pour dormir ou se reposer'),
(220, 'chien', 'Animaux', 'Un animal domestique souvent loyal'),
(221, 'fleur', 'Nature', 'Partie d'une plante utilisée pour sa beauté'),
(222, 'cuisine', 'Activités', 'L'art de préparer et de cuisiner des aliments'),
(223, 'train', 'Transport', 'Un moyen de transport sur rails'),
(224, 'tableau', 'Art', 'Une œuvre d'art visuelle'),
(225, 'cœur', 'Anatomie', 'Un organe vital dans le corps humain'),
(226, 'bateau', 'Transport', 'Un véhicule flottant utilisé pour naviguer sur l'eau'),
(227, 'oiseau', 'Animaux', 'Un animal volant avec des plumes'),
(228, 'musique', 'Art', 'Expression artistique par le son'),
(229, 'école', 'Éducation', 'Lieu où l'on apprend'),
(230, 'cheminée', 'Architecture', 'Une structure pour évacuer la fumée des feux');

INSERT INTO Words (word_id, word, category, definition) VALUES
(231, 'jouet', 'Loisirs', 'Un objet utilisé pour jouer'),
(232, 'vent', 'Météorologie', 'Le mouvement de l'air dans l'atmosphère'),
(233, 'sac', 'Accessoires', 'Un conteneur portatif utilisé pour transporter des objets'),
(234, 'nuit', 'Temps', 'La période entre le coucher et le lever du soleil'),
(235, 'légume', 'Aliments', 'Un aliment issu de plantes comestibles'),
(236, 'crayon', 'Écriture', 'Un outil pour écrire ou dessiner'),
(237, 'ballon', 'Sports', 'Un objet gonflable utilisé pour jouer'),
(238, 'téléphone', 'Technologie', 'Appareil de communication électronique'),
(239, 'ventre', 'Anatomie', 'La partie du corps entre la poitrine et les hanches'),
(240, 'bureau', 'Mobilier', 'Un meuble pour travailler ou étudier'),
(241, 'cuisinier', 'Métiers', 'Une personne qui prépare des repas'),
(242, 'fête', 'Célébration', 'Un événement joyeux avec des gens'),
(243, 'brosse', 'Outils', 'Un outil avec des poils utilisé pour nettoyer ou peindre'),
(244, 'cheveux', 'Anatomie', 'Les fils qui poussent sur la tête humaine'),
(245, 'araignée', 'Animaux', 'Un petit arthropode à huit pattes'),
(246, 'télévision', 'Technologie', 'Un appareil pour recevoir des signaux audiovisuels'),
(247, 'carré', 'Formes', 'Une forme géométrique avec quatre côtés égaux'),
(248, 'pluie', 'Météorologie', 'Des gouttes d'eau tombant du ciel'),
(249, 'porte', 'Architecture', 'Un dispositif pour fermer une ouverture'),
(250, 'couverture', 'Textiles', 'Un morceau de tissu utilisé pour se couvrir'),
(251, 'planète', 'Astronomie', 'Un objet céleste orbitant autour d'une étoile'),
(252, 'clé', 'Outils', 'Un petit outil utilisé pour ouvrir ou fermer une serrure'),
(253, 'jeu', 'Loisirs', 'Activité divertissante avec des règles'),
(254, 'café', 'Boissons', 'Une boisson chaude souvent faite à partir de grains de café'),
(255, 'sable', 'Géographie', 'Petites particules de roche utilisées pour former des plages'),
(256, 'vélo', 'Transport', 'Un moyen de transport à deux roues'),
(257, 'porte', 'Architecture', 'Un dispositif pour fermer une ouverture'),
(258, 'chaussure', 'Vêtements', 'Un accessoire porté sur le pied'),
(259, 'sourire', 'Expressions faciales', 'Une expression du visage qui montre de la joie'),
(260, 'jeu', 'Loisirs', 'Activité divertissante avec des règles'),
(261, 'guitare', 'Musique', 'Un instrument à cordes pincées'),
(262, 'bateau', 'Transport', 'Un véhicule flottant utilisé pour naviguer sur l'eau'),
(263, 'cuisine', 'Activités', 'L'art de préparer et de cuisiner des aliments'),
(264, 'bonheur', 'Émotions', 'Un état de bien-être et de satisfaction'),
(265, 'tableau', 'Art', 'Une œuvre d'art visuelle'),
(266, 'ballon', 'Sports', 'Un objet gonflable utilisé pour jouer'),
(267, 'soleil', 'Astronomie', 'L'étoile centrale de notre système solaire'),
(268, 'portable', 'Technologie', 'Un ordinateur personnel compact'),
(269, 'clé', 'Outils', 'Un petit outil utilisé pour ouvrir ou fermer une serrure'),
(270, 'maison', 'Habitat', 'Lieu où l'on habite'),
(271, 'chocolat', 'Aliments', 'Une douceur sucrée souvent faite à partir de cacao'),
(272, 'jour', 'Temps', 'La période de temps pendant laquelle le soleil est au-dessus de l'horizon'),
(273, 'souris', 'Animaux', 'Un petit mammifère rongeur'),
(274, 'ciel', 'Astronomie', 'L'espace visible au-dessus de la Terre'),
(275, 'cœur', 'Anatomie', 'Un organe vital dans le corps humain');

INSERT INTO Words (word_id, word, category, definition) VALUES
(276, 'avion', 'Transport', 'Un véhicule qui vole dans les airs'),
(277, 'chat', 'Animaux', 'Un mammifère domestique souvent aimé par les gens'),
(278, 'chapeau', 'Accessoires', 'Un accessoire porté sur la tête'),
(279, 'plage', 'Nature', 'Bord de mer où l'on peut se détendre'),
(280, 'bonjour', 'Salutation', 'Un mot utilisé pour dire bonjour'),
(281, 'ordinateur', 'Technologie', 'Appareil électronique pour traiter des données'),
(282, 'livre', 'Culture', 'Un ensemble de pages reliées contenant des informations ou une histoire'),
(283, 'fleur', 'Nature', 'Partie d'une plante utilisée pour sa beauté'),
(284, 'brosse', 'Outils', 'Un outil avec des poils utilisé pour nettoyer ou peindre'),
(285, 'bouteille', 'Contenants', 'Un récipient pour stocker des liquides'),
(286, 'ciel', 'Astronomie', 'L'espace visible au-dessus de la Terre'),
(287, 'pluie', 'Météorologie', 'Des gouttes d'eau tombant du ciel'),
(288, 'voiture', 'Transport', 'Moyen de déplacement terrestre à moteur'),
(289, 'mère', 'Famille', 'Femme qui a donné naissance à un enfant'),
(290, 'fête', 'Célébration', 'Un événement joyeux avec des gens'),
(291, 'cuisine', 'Activités', "L'art de préparer et de cuisiner des aliments"),
(292, 'carte', 'Papeterie', 'Un morceau de papier avec des informations ou des illustrations'),
(293, 'sable', 'Nature', 'Petites particules de roche utilisées pour former des plages'),
(294, 'chien', 'Animaux', 'Un animal domestique souvent loyal'),
(295, 'télévision', 'Technologie', 'Un appareil pour recevoir des signaux audiovisuels'),
(296, 'jardin', 'Nature', 'Un espace extérieur aménagé avec des plantes et des fleurs'),
(297, 'café', 'Boissons', 'Une boisson chaude souvent faite à partir de grains de café'),
(298, 'cœur', 'Anatomie', 'Un organe vital dans le corps humain'),
(299, 'route', 'Géographie', 'Un chemin ou une voie pour se déplacer'),
(300, 'oiseau', 'Animaux', 'Un animal volant avec des plumes'),
(301, 'piscine', 'Loisirs', 'Un bassin artificiel rempli d'eau pour nager'),
(302, 'sourire', 'Expressions faciales', 'Une expression du visage qui montre de la joie'),
(303, 'table', 'Mobilier', 'Un meuble plat avec des jambes pour supporter des objets'),
(304, 'guitare', 'Musique', 'Un instrument à cordes pincées'),
(305, 'sac', 'Accessoires', 'Un conteneur portatif utilisé pour transporter des objets'),
(306, 'ciseaux', 'Outils', 'Un outil tranchant utilisé pour couper'),
(307, 'jouet', 'Loisirs', 'Un objet utilisé pour jouer'),
(308, 'chemise', 'Vêtements', 'Un vêtement porté sur le torse'),
(309, 'maison', 'Habitat', 'Lieu où l'on habite'),
(310, 'carte', 'Papeterie', 'Un morceau de papier avec des informations ou des illustrations'),
(311, 'école', 'Éducation', "Lieu où l'on apprend"),
(312, 'portable', 'Technologie', 'Un ordinateur personnel compact'),
(313, 'piano', 'Musique', 'Un instrument de musique à cordes frappées'),
(314, 'plante', 'Nature', 'Un organisme végétal'),
(315, 'pomme', 'Aliments', 'Un fruit croquant et juteux'),
(316, 'fenêtre', 'Architecture', 'Une ouverture dans un mur pour laisser entrer la lumière et l'air'),
(317, 'crayon', 'Écriture', 'Un outil pour écrire ou dessiner'),
(318, 'chocolat', 'Aliments', 'Une douceur sucrée souvent faite à partir de cacao'),
(319, 'lune', 'Astronomie', 'Le satellite naturel de la Terre'),
(320, 'ballon', 'Sports', 'Un objet gonflable utilisé pour jouer'),
(321, 'souris', 'Animaux', 'Un petit mammifère rongeur'),
(322, 'cheminée', 'Architecture', 'Une structure pour évacuer la fumée des feux'),
(323, 'livre', 'Culture', 'Un ensemble de pages reliées contenant des informations ou une histoire');

INSERT INTO Words (word_id, word, category, definition) VALUES
(324, 'fenêtre', 'Architecture', 'Une ouverture dans un mur pour laisser entrer la lumière et l'air'),
(325, 'étoile', 'Astronomie', 'Un objet lumineux dans le ciel nocturne'),
(326, 'pluie', 'Météorologie', 'Des gouttes d'eau tombant du ciel'),
(327, 'bateau', 'Transport', 'Un véhicule flottant utilisé pour naviguer sur l'eau'),
(328, 'soleil', 'Astronomie', 'L'étoile centrale de notre système solaire'),
(329, 'voiture', 'Transport', 'Moyen de déplacement terrestre à moteur'),
(330, 'vélo', 'Transport', 'Un moyen de transport à deux roues'),
(331, 'train', 'Transport', 'Un moyen de transport sur rails'),
(332, 'avion', 'Transport', 'Un véhicule qui vole dans les airs'),
(333, 'maison', 'Habitat', 'Lieu où l'on habite'),
(334, 'arbre', 'Nature', 'Une plante vivante avec un tronc et des branches'),
(335, 'fleur', 'Nature', 'Partie d'une plante utilisée pour sa beauté'),
(336, 'animal', 'Animaux', 'Un être vivant non végétal'),
(337, 'oiseau', 'Animaux', 'Un animal volant avec des plumes'),
(338, 'chat', 'Animaux', 'Un mammifère domestique souvent aimé par les gens'),
(339, 'chien', 'Animaux', 'Un animal domestique souvent loyal'),
(340, 'poisson', 'Animaux', 'Un animal aquatique avec des branchies et des nageoires'),
(341, 'insecte', 'Animaux', 'Un petit animal à six pattes avec un exosquelette'),
(342, 'serpent', 'Animaux', 'Un reptile sans membres'),
(343, 'pomme', 'Aliments', 'Un fruit croquant et juteux'),
(344, 'banane', 'Aliments', 'Un fruit jaune et courbé'),
(345, 'pain', 'Aliments', 'Un aliment de base fait à partir de farine'),
(346, 'chocolat', 'Aliments', 'Une douceur sucrée souvent faite à partir de cacao'),
(347, 'pâtes', 'Aliments', 'Des morceaux de pâte alimentaire'),
(348, 'riz', 'Aliments', 'Un grain alimentaire de base pour de nombreuses cultures'),
(349, 'viande', 'Aliments', 'Tissu musculaire d'animaux utilisé comme nourriture'),
(350, 'eau', 'Nourriture', 'Un liquide transparent nécessaire à la vie'),
(351, 'jus', 'Boissons', 'Un liquide extrait de fruits ou de légumes'),
(352, 'café', 'Boissons', 'Une boisson chaude souvent faite à partir de grains de café'),
(353, 'thé', 'Boissons', 'Une boisson chaude ou froide infusée à partir de feuilles de thé'),
(354, 'jus', 'Boissons', 'Un liquide extrait de fruits ou de légumes'),
(355, 'bière', 'Boissons', 'Une boisson alcoolisée à base de céréales fermentées'),
(356, 'vin', 'Boissons', 'Une boisson alcoolisée à base de raisins fermentés'),
(357, 'eau', 'Boissons', 'Un liquide transparent nécessaire à la vie'),
(358, 'téléphone', 'Technologie', 'Appareil de communication électronique'),
(359, 'ordinateur', 'Technologie', 'Appareil électronique pour traiter des données'),
(360, 'télévision', 'Technologie', 'Un appareil pour recevoir des signaux audiovisuels'),
(361, 'appareil', 'Technologie', 'Un dispositif mécanique ou électronique'),
(362, 'caméra', 'Technologie', 'Un appareil pour enregistrer des images ou des vidéos'),
(363, 'tablette', 'Technologie', 'Un petit ordinateur portable avec un écran tactile'),
(364, 'smartphone', 'Technologie', 'Un téléphone mobile avec des fonctionnalités avancées'),
(365, 'montre', 'Accessoires', 'Un dispositif pour mesurer le temps'),
(366, 'bague', 'Accessoires', 'Un petit ornement porté sur le doigt'),
(367, 'collier', 'Accessoires', 'Un bijou porté autour du cou'),
(368, 'bracelet', 'Accessoires', 'Un bijou porté autour du poignet'),
(369, 'chaussure', 'Vêtements', 'Un accessoire porté sur le pied'),
(370, 'chemise', 'Vêtements', 'Un vêtement porté sur le torse'),
(371, 'pantalon', 'Vêtements', 'Un vêtement porté sur les jambes'),
(372, 'robe', 'Vêtements', 'Un vêtement féminin souvent porté lors d'occasions spéciales');

INSERT INTO Words (word_id, word, category, definition) VALUES
(373, 'crayon', 'Écriture', 'Un outil pour écrire ou dessiner'),
(374, 'stylo', 'Écriture', 'Un instrument pour écrire avec de l'encre'),
(375, 'papier', 'Papeterie', 'Une feuille utilisée pour écrire ou dessiner'),
(376, 'cahier', 'Papeterie', 'Un livre avec des pages pour écrire'),
(377, 'agenda', 'Papeterie', 'Un livre pour noter des rendez-vous ou des tâches'),
(378, 'classeur', 'Papeterie', 'Un outil de rangement pour des feuilles de papier'),
(379, 'feuille', 'Papeterie', 'Une partie d'un arbre utilisée pour écrire ou dessiner'),
(380, 'carton', 'Matériaux', 'Un matériau rigide et épais utilisé pour fabriquer des boîtes'),
(381, 'verre', 'Matériaux', 'Un matériau transparent souvent utilisé pour les fenêtres ou les récipients'),
(382, 'bois', 'Matériaux', 'Le matériau dur issu des arbres utilisé dans la construction'),
(383, 'plastique', 'Matériaux', 'Un matériau synthétique malléable souvent utilisé dans la fabrication d'objets'),
(384, 'métal', 'Matériaux', 'Un matériau dur et brillant souvent utilisé dans la fabrication de machines'),
(385, 'pierre', 'Matériaux', 'Un matériau solide issu de la terre souvent utilisé dans la construction'),
(386, 'coton', 'Matériaux', 'Une fibre naturelle douce souvent utilisée dans la fabrication de vêtements'),
(387, 'laine', 'Matériaux', 'Une fibre naturelle douce souvent utilisée dans la fabrication de vêtements chauds'),
(388, 'soie', 'Matériaux', 'Une fibre naturelle lisse et brillante souvent utilisée dans la fabrication de tissus'),
(389, 'or', 'Matériaux', 'Un métal précieux jaune souvent utilisé dans la fabrication de bijoux'),
(390, 'argent', 'Matériaux', 'Un métal précieux brillant souvent utilisé dans la fabrication de bijoux'),
(391, 'diamant', 'Matériaux', 'Une pierre précieuse dure et transparente souvent utilisée dans la fabrication de bijoux'),
(392, 'rubis', 'Matériaux', 'Une pierre précieuse rouge souvent utilisée dans la fabrication de bijoux'),
(393, 'saphir', 'Matériaux', 'Une pierre précieuse bleue souvent utilisée dans la fabrication de bijoux'),
(394, 'émeraude', 'Matériaux', 'Une pierre précieuse verte souvent utilisée dans la fabrication de bijoux'),
(395, 'perle', 'Matériaux', 'Une petite sphère brillante souvent utilisée dans la fabrication de bijoux'),
(396, 'argent', 'Matériaux', 'Un métal précieux brillant souvent utilisé dans la fabrication de bijoux'),
(397, 'cuir', 'Matériaux', 'Une peau animale tannée souvent utilisée dans la fabrication de vêtements et d'accessoires'),
(398, 'céramique', 'Matériaux', 'Un matériau dur et non métallique souvent utilisé dans la fabrication d'objets décoratifs'),
(399, 'poterie', 'Matériaux', 'Des objets en argile cuite souvent fabriqués à la main'),
(400, 'verre', 'Matériaux', 'Un matériau transparent souvent utilisé pour les fenêtres ou les récipients'),
(401, 'sable', 'Matériaux', 'Des petites particules de roche souvent utilisées dans la construction'),
(402, 'ciment', 'Matériaux', 'Un liant minéral souvent utilisé dans la construction pour coller des matériaux'),
(403, 'béton', 'Matériaux', 'Un mélange de ciment, de sable, de gravier et d'eau souvent utilisé dans la construction'),
(404, 'argile', 'Matériaux', 'Une terre molle souvent utilisée dans la poterie et la céramique'),
(405, 'bois', 'Matériaux', 'Le matériau dur issu des arbres utilisé dans la construction'),
(406, 'pierre', 'Matériaux', 'Un matériau solide issu de la terre souvent utilisé dans la construction'),
(407, 'acier', 'Matériaux', 'Un alliage métallique dur et résistant souvent utilisé dans la construction et la fabrication de machines'),
(408, 'fer', 'Matériaux', 'Un métal dur souvent utilisé dans la construction et la fabrication de machines'),
(409, 'aluminium', 'Matériaux', 'Un métal léger souvent utilisé dans la construction et la fabrication de véhicules'),
(410, 'plastique', 'Matériaux', 'Un matériau synthétique malléable souvent utilisé dans la fabrication d'objets'),
(411, 'verre', 'Matériaux', 'Un matériau transparent souvent utilisé pour les fenêtres ou les récipients'),
(412, 'papier', 'Matériaux', 'Une feuille utilisée pour écrire ou dessiner'),
(413, 'carton', 'Matériaux', 'Un matériau rigide et épais utilisé pour fabriquer des boîtes'),
(414, 'toile', 'Matériaux', 'Un tissu épais souvent utilisé pour la peinture'),
(415, 'plastique', 'Matériaux', 'Un matériau synthétique malléable souvent utilisé dans la fabrication d'objets'),
(416, 'caoutchouc', 'Matériaux', 'Un matériau élastique souvent utilisé dans la fabrication de pneus et de produits étanches'),
(417, 'cuir', 'Matériaux', 'Une peau animale tannée souvent utilisée dans la fabrication de vêtements et d'accessoires'),
(418, 'pierre', 'Matériaux', 'Un matériau solide issu de la terre souvent utilisé dans la construction'),
(419, 'verre', 'Matériaux', 'Un matériau transparent souvent utilisé pour les fenêtres ou les récipients'),
(420, 'cuir', 'Matériaux', 'Une peau animale tannée souvent utilisée dans la fabrication de vêtements et d'accessoires'),
(421, 'papier', 'Matériaux', 'Une feuille utilisée pour écrire ou dessiner');

INSERT INTO Words (word_id, word, category, definition) VALUES
(422, 'cheval', 'Animaux', 'Un grand mammifère équidé souvent utilisé comme animal de travail ou de loisir'),
(423, 'vache', 'Animaux', 'Un grand mammifère bovin souvent élevé pour sa viande et son lait'),
(424, 'mouton', 'Animaux', 'Un mammifère domestique souvent élevé pour sa laine et sa viande'),
(425, 'cochon', 'Animaux', 'Un mammifère omnivore souvent élevé pour sa viande'),
(426, 'poulet', 'Animaux', 'Un jeune oiseau domestique souvent élevé pour sa viande et ses œufs'),
(427, 'canard', 'Animaux', 'Un oiseau aquatique souvent élevé pour sa viande et ses œufs'),
(428, 'oie', 'Animaux', 'Un grand oiseau aquatique souvent élevé pour sa viande et ses plumes'),
(429, 'lapin', 'Animaux', 'Un petit mammifère souvent élevé comme animal de compagnie ou pour sa viande'),
(430, 'souris', 'Animaux', 'Un petit mammifère rongeur souvent considéré comme une nuisance dans les habitations'),
(431, 'éléphant', 'Animaux', 'Un grand mammifère pachyderme souvent caractérisé par sa trompe'),
(432, 'lion', 'Animaux', 'Un grand félin carnivore souvent considéré comme le roi des animaux'),
(433, 'tigre', 'Animaux', 'Un grand félin carnivore souvent rayé de noir sur orange'),
(434, 'ours', 'Animaux', 'Un grand mammifère carnivore souvent caractérisé par sa fourrure'),
(435, 'renard', 'Animaux', 'Un mammifère carnivore souvent caractérisé par son pelage roux'),
(436, 'loup', 'Animaux', 'Un mammifère carnivore souvent considéré comme un prédateur'),
(437, 'guépard', 'Animaux', 'Un grand félin carnivore souvent caractérisé par sa vitesse'),
(438, 'panthère', 'Animaux', 'Un grand félin carnivore souvent caractérisé par sa couleur noire'),
(439, 'lynx', 'Animaux', 'Un félin souvent caractérisé par ses oreilles pointues et son pelage tacheté'),
(440, 'léopard', 'Animaux', 'Un grand félin carnivore souvent caractérisé par ses taches'),
(441, 'girafe', 'Animaux', 'Un grand mammifère herbivore souvent caractérisé par son long cou'),
(442, 'hippopotame', 'Animaux', 'Un grand mammifère herbivore semi-aquatique souvent caractérisé par sa masse'),
(443, 'rhinocéros', 'Animaux', 'Un grand mammifère herbivore souvent caractérisé par sa corne'),
(444, 'zèbre', 'Animaux', 'Un grand mammifère herbivore souvent caractérisé par ses rayures'),
(445, 'chameau', 'Animaux', 'Un grand mammifère herbivore souvent utilisé comme animal de bât'),
(446, 'âne', 'Animaux', 'Un petit mammifère équidé souvent utilisé comme animal de travail'),
(447, 'panda', 'Animaux', 'Un grand mammifère herbivore souvent caractérisé par ses taches noires et blanches'),
(448, 'koala', 'Animaux', 'Un petit marsupial herbivore souvent associé à l'Australie'),
(449, 'singe', 'Animaux', 'Un mammifère souvent caractérisé par son agilité et sa queue préhensile'),
(450, 'perroquet', 'Animaux', 'Un oiseau souvent coloré et doté de la capacité de reproduire des sons'),
(451, 'pieuvre', 'Animaux', 'Un mollusque souvent caractérisé par ses huit bras et sa capacité à changer de couleur'),
(452, 'requin', 'Animaux', 'Un grand poisson carnivore souvent caractérisé par ses dents pointues'),
(453, 'dauphin', 'Animaux', 'Un mammifère marin souvent caractérisé par son intelligence et sa capacité à sauter hors de l'eau'),
(454, 'tortue', 'Animaux', 'Un reptile souvent caractérisé par sa carapace dure'),
(455, 'crocodile', 'Animaux', 'Un grand reptile souvent caractérisé par ses mâchoires puissantes et sa peau écailleuse'),
(456, 'serpent', 'Animaux', 'Un reptile sans membres souvent caractérisé par sa langue fourchue'),
(457, 'lézard', 'Animaux', 'Un petit reptile souvent caractérisé par sa capacité à changer de couleur'),
(458, 'gecko', 'Animaux', 'Un petit reptile souvent caractérisé par ses pattes adhésives'),
(459, 'grenouille', 'Animaux', 'Un amphibien souvent caractérisé par ses sauts et ses vocalisations'),
(460, 'salamandre', 'Animaux', 'Un amphibien souvent caractérisé par sa peau lisse et son apparence reptilienne'),
(461, 'anguille', 'Animaux', 'Un poisson souvent caractérisé par son corps serpentiforme'),
(462, 'méduse', 'Animaux', 'Un cnidaire souvent caractérisé par son corps translucide et ses tentacules urticants'),
(463, 'éponge', 'Animaux', 'Un animal aquatique souvent caractérisé par sa capacité à filtrer l'eau'),
(464, 'moule', 'Animaux', 'Un mollusque souvent utilisé comme aliment'),
(465, 'escargot', 'Animaux', 'Un mollusque souvent caractérisé par sa coquille spiralée'),
(466, 'crabe', 'Animaux', 'Un crustacé souvent caractérisé par sa carapace et ses pinces'),
(467, 'crevette', 'Animaux', 'Un crustacé souvent utilisé comme aliment'),
(468, 'homard', 'Animaux', 'Un crustacé souvent considéré comme un mets de luxe');

INSERT INTO Words (word_id, word, category, definition) VALUES
(469, 'pomme', 'Aliments', 'Un fruit croquant et juteux'),
(470, 'poire', 'Aliments', 'Un fruit sucré souvent en forme de poire'),
(471, 'banane', 'Aliments', 'Un fruit jaune et courbé'),
(472, 'orange', 'Aliments', 'Un agrume souvent utilisé pour son jus'),
(473, 'citron', 'Aliments', 'Un agrume acide souvent utilisé pour son jus et son zeste'),
(474, 'fraise', 'Aliments', 'Un petit fruit rouge et sucré souvent utilisé dans les desserts'),
(475, 'framboise', 'Aliments', 'Un petit fruit rouge souvent utilisé dans les desserts et les confitures'),
(476, 'mûre', 'Aliments', 'Un petit fruit noir et sucré souvent utilisé dans les desserts et les confitures'),
(477, 'myrtille', 'Aliments', 'Un petit fruit bleu foncé souvent utilisé dans les desserts et les confitures'),
(478, 'raisin', 'Aliments', 'Un fruit sucré souvent utilisé pour faire du vin'),
(479, 'ananas', 'Aliments', 'Un fruit tropical souvent utilisé pour son goût sucré et son jus'),
(480, 'kiwi', 'Aliments', 'Un petit fruit vert et velu souvent utilisé pour son goût acidulé'),
(481, 'pamplemousse', 'Aliments', 'Un agrume souvent utilisé pour son jus et son goût amer'),
(482, 'cerise', 'Aliments', 'Un petit fruit rouge ou noir souvent utilisé dans les desserts'),
(483, 'abricot', 'Aliments', 'Un petit fruit orange souvent utilisé dans les desserts et les confitures'),
(484, 'abricot', 'Aliments', 'Un petit fruit orange souvent utilisé dans les desserts et les confitures'),
(485, 'tomate', 'Aliments', 'Un fruit rouge souvent utilisé comme légume dans la cuisine'),
(486, 'carotte', 'Aliments', 'Un légume orange souvent utilisé dans les salades et les soupes'),
(487, 'pomme de terre', 'Aliments', 'Un tubercule souvent utilisé comme légume dans la cuisine'),
(488, 'oignon', 'Aliments', 'Un légume souvent utilisé comme condiment dans la cuisine'),
(489, 'ail', 'Aliments', 'Un bulbe souvent utilisé comme condiment dans la cuisine'),
(490, 'brocoli', 'Aliments', 'Un légume vert souvent utilisé comme accompagnement dans les plats'),
(491, 'chou', 'Aliments', 'Un légume vert souvent utilisé dans les soupes et les salades'),
(492, 'salade', 'Aliments', 'Un mélange de légumes souvent servi cru avec une vinaigrette'),
(493, 'épinard', 'Aliments', 'Un légume vert souvent utilisé dans les plats cuisinés'),
(494, 'courgette', 'Aliments', 'Un légume vert allongé souvent utilisé dans les plats cuisinés'),
(495, 'aubergine', 'Aliments', 'Un légume violet souvent utilisé dans les plats cuisinés'),
(496, 'poivron', 'Aliments', 'Un légume souvent utilisé dans les plats cuisinés'),
(497, 'concombre', 'Aliments', 'Un légume vert souvent utilisé dans les salades'),
(498, 'champignon', 'Aliments', 'Un champignon souvent utilisé dans la cuisine'),
(499, 'haricot', 'Aliments', 'Une plante légumineuse souvent utilisée dans les plats cuisinés'),
(500, 'lentille', 'Aliments', 'Une petite légumineuse souvent utilisée dans les plats cuisinés'),
(501, 'pois', 'Aliments', 'Une légumineuse souvent utilisée dans les plats cuisinés'),
(502, 'blé', 'Aliments', 'Une céréale souvent utilisée pour faire du pain et des pâtes'),
(503, 'riz', 'Aliments', 'Une céréale souvent utilisée comme aliment de base dans de nombreuses cultures'),
(504, 'avoine', 'Aliments', 'Une céréale souvent utilisée pour faire du porridge et des biscuits'),
(505, 'maïs', 'Aliments', 'Une céréale souvent utilisée comme aliment de base dans les Amériques'),
(506, 'orge', 'Aliments', 'Une céréale souvent utilisée pour faire de la bière et de la soupe'),
(507, 'seigle', 'Aliments', 'Une céréale souvent utilisée pour faire du pain et de la vodka'),
(508, 'quinoa', 'Aliments', 'Une pseudo-céréale souvent utilisée comme alternative au riz et au blé'),
(509, 'mil', 'Aliments', 'Une céréale souvent cultivée dans les régions arides de l'Afrique et de l'Asie'),
(510, 'sorgho', 'Aliments', 'Une céréale souvent cultivée dans les régions semi-arides de l'Afrique et de l'Asie'),
(511, 'chanvre', 'Aliments', 'Une plante souvent utilisée pour ses graines riches en protéines et en acides gras'),
(512, 'millet', 'Aliments', 'Une céréale souvent cultivée dans les régions sèches de l'Afrique et de l'Asie');




